version: '3.8'
services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - auth-network
  mongodb:
    image: mongo:6
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - auth-network
networks:
  auth-network:
    driver: bridge
volumes:
  mongodb_data: